-- Enrollment & Registration tables
-- Note: Flyway is disabled in this project. Tables are created by Hibernate ddl-auto: update.
-- This file is for reference only.

CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    college VARCHAR(200),
    department VARCHAR(200),
    duration_years INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_courses_code ON courses (code);

CREATE TABLE IF NOT EXISTS course_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    course_id BIGINT NOT NULL REFERENCES courses(id),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    credits INTEGER NOT NULL,
    semester INTEGER NOT NULL,
    year INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_course_units_course ON course_units (course_id);
CREATE INDEX IF NOT EXISTS idx_course_units_semester ON course_units (course_id, semester, year);

CREATE TABLE IF NOT EXISTS enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    student_id VARCHAR(100) NOT NULL,
    course_unit_id BIGINT NOT NULL REFERENCES course_units(id),
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    grade DECIMAL(5,2),
    enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_enrollments_student ON enrollments (student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_course_unit ON enrollments (course_unit_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_enrollments_unique ON enrollments (student_id, course_unit_id);
