CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO tenants (code, name) VALUES ('demo', 'University Application Portal');

CREATE TABLE contact_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    name VARCHAR(200) NOT NULL,
    email VARCHAR(320) NOT NULL,
    subject VARCHAR(500) NOT NULL,
    message VARCHAR(10000) NOT NULL,
    source VARCHAR(64) NOT NULL DEFAULT 'contact-page',
    status VARCHAR(32) NOT NULL DEFAULT 'NEW',
    ip_address VARCHAR(64),
    emailed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_contact_tenant_created ON contact_submissions (tenant_id, created_at);
