CREATE TABLE fee_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    item_name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    year_level VARCHAR(50) NOT NULL,
    semester VARCHAR(50) NOT NULL,
    academic_year VARCHAR(20) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'UGX',
    college VARCHAR(200) NOT NULL,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_fee_assignments_tenant ON fee_assignments (tenant_id);
CREATE INDEX idx_fee_assignments_academic_year ON fee_assignments (academic_year);
CREATE INDEX idx_fee_assignments_college ON fee_assignments (college);
CREATE INDEX idx_fee_assignments_year_semester ON fee_assignments (year_level, semester);
