CREATE TABLE student_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    student_id BIGINT NOT NULL,
    fee_assignment_id BIGINT NOT NULL REFERENCES fee_assignments(id),
    amount NUMERIC(14, 2) NOT NULL,
    paid_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    due_date DATE,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_student_fees_tenant ON student_fees (tenant_id);
CREATE INDEX idx_student_fees_student ON student_fees (student_id);
CREATE INDEX idx_student_fees_fee_assignment ON student_fees (fee_assignment_id);
CREATE INDEX idx_student_fees_status ON student_fees (status);
