CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    from_user_id BIGINT NOT NULL,
    to_user_id BIGINT NOT NULL,
    subject VARCHAR(500) NOT NULL,
    body TEXT NOT NULL,
    sender_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    recipient_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    sender_starred BOOLEAN NOT NULL DEFAULT FALSE,
    recipient_starred BOOLEAN NOT NULL DEFAULT FALSE,
    sender_archived BOOLEAN NOT NULL DEFAULT FALSE,
    recipient_archived BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_messages_tenant ON messages (tenant_id);
CREATE INDEX idx_messages_from_user ON messages (from_user_id);
CREATE INDEX idx_messages_to_user ON messages (to_user_id);
CREATE INDEX idx_messages_created ON messages (created_at DESC);

CREATE TABLE message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    url VARCHAR(500) NOT NULL,
    name VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_message_attachments_message ON message_attachments (message_id);

CREATE TABLE message_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    user_id BIGINT NOT NULL,
    to_user_id BIGINT,
    subject VARCHAR(500) DEFAULT '(no subject)',
    body TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_message_drafts_user ON message_drafts (user_id);
