CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenants(id),
    prn VARCHAR(50) UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    other_names VARCHAR(100),
    email VARCHAR(320) NOT NULL,
    phone_number VARCHAR(20),
    gender VARCHAR(20),
    date_of_birth TIMESTAMP,
    nationality VARCHAR(200),
    district VARCHAR(200),
    subcounty VARCHAR(200),
    village VARCHAR(200),
    program_choice_1 VARCHAR(200),
    program_choice_2 VARCHAR(200),
    program_choice_3 VARCHAR(200),
    study_mode VARCHAR(50),
    academic_year VARCHAR(20),
    semester VARCHAR(20),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    review_status VARCHAR(32),
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewer_notes TEXT,
    uce_result JSONB,
    uace_result JSONB,
    documents JSONB,
    extras JSONB,
    fee_paid NUMERIC(14, 2),
    fee_required NUMERIC(14, 2),
    fee_currency VARCHAR(3) DEFAULT 'UGX',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_applications_tenant ON applications (tenant_id);
CREATE INDEX idx_applications_prn ON applications (prn);
CREATE INDEX idx_applications_email ON applications (email);
CREATE INDEX idx_applications_status ON applications (status);
CREATE INDEX idx_applications_review_status ON applications (review_status);
CREATE INDEX idx_applications_submitted ON applications (submitted_at);
